# Generated by Django 3.2.18 on 2023-04-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0024_rename_history_additem_creat_history_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='interstate',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='additem',
            name='intrastate',
            field=models.CharField(default='', max_length=255),
        ),
    ]
