# Generated by Django 4.1.7 on 2023-05-28 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0031_alter_additem_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additem',
            name='date',
        ),
    ]
