# Generated by Django 4.1.7 on 2023-05-28 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0032_remove_additem_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='additem',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
