# Generated by Django 4.1.7 on 2023-05-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zohoapp', '0035_remove_salesorder_s_date_salesorder_sales_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sales_item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.TextField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('hsn', models.TextField(blank=True, max_length=255, null=True)),
                ('tax', models.IntegerField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, max_length=255, null=True)),
                ('rate', models.TextField(blank=True, max_length=255, null=True)),
                ('inv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='zohoapp.salesorder')),
            ],
        ),
    ]
